#!/usr/bin/env python3
"""Build README.md (awesome-list style) from the catalog in generate.py."""
from __future__ import annotations

from pathlib import Path

from generate import PROGRAMS, MARKUP

ROOT = Path(__file__).resolve().parent
TOTAL = len(PROGRAMS) + len(MARKUP)


def table(entries: dict[str, tuple[str, str]]) -> str:
    rows = ["| Language | File |", "| --- | --- |"]
    for name, (rel, _) in sorted(entries.items(), key=lambda kv: kv[0].lower()):
        rows.append(f"| {name} | [`{rel}`](languages/{rel}) |")
    return "\n".join(rows)


README = f"""# Awesome Hello Languages [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)

> One repository. One greeting. {TOTAL} programming languages and data formats.

A curated, runnable collection of **"Hello, World!"** — the same line printed in
as many different languages as possible. Compiled, interpreted, functional,
logic, stack-based, esoteric, hardware-description, query and markup languages
all live side by side under [`languages/`](languages).

Every file is generated by [`generate.py`](generate.py), so the catalog is a
single source of truth: add an entry to the map, re-run the script, and the
greeting appears in a new tongue.

## Contents

- [Stats](#stats)
- [Programming languages](#programming-languages)
- [Markup, data & build formats](#markup-data--build-formats)
- [How it works](#how-it-works)
- [Run a few](#run-a-few)
- [Contributing](#contributing)

## Stats

| Metric | Count |
| --- | --- |
| Programming languages | {len(PROGRAMS)} |
| Markup / data / build formats | {len(MARKUP)} |
| **Total greetings** | **{TOTAL}** |

## Programming languages

{table(PROGRAMS)}

## Markup, data & build formats

{table(MARKUP)}

## How it works

The whole repo is driven by one catalog in [`generate.py`](generate.py):

```python
PROGRAMS = {{
    "Rust": ("rust/hello.rs", 'fn main() {{ println!("Hello, World!"); }}'),
    # ...
}}
```

Run it to (re)materialize every file:

```bash
python generate.py        # writes languages/**/hello.*
python build_readme.py    # regenerates this README
```

## Run a few

```bash
python  languages/python/hello.py
ruby    languages/ruby/hello.rb
node    languages/javascript/hello.js
go      run languages/go/hello.go
bash    languages/bash/hello.sh
lua     languages/lua/hello.lua
```

## Contributing

1. Add a `"Language": ("dir/hello.ext", "source")` entry to `PROGRAMS`
   (or `MARKUP`) in `generate.py`.
2. Run `python generate.py && python build_readme.py`.
3. Open a pull request. Keep the output exactly `Hello, World!`.

## License

[MIT](LICENSE) — do whatever you like.
"""


def main() -> None:
    (ROOT / "README.md").write_text(README, encoding="utf-8")
    print(f"README.md written ({TOTAL} entries)")


if __name__ == "__main__":
    main()
